# TODO: make this more reusable
type: s3-downloader
version: 0.0.1

inputTypes:
  name:
    type: string
    default: my-s3-downloader
  eventGatewaySpace:
    type: string
    required: true
  eventGatewayApiKey:
    type: string
    required: true

components:
  downloaderLambda:
    type: aws-lambda
    inputs:
      name: ${input.name}
      handler: downloader.handler
      env:
        EVENT_GATEWAY_APIKEY: ${inputs.eventGatewayApiKey}
        FILES_TABLE: serverless-components-files
  downloaderSubscription:
    type: eventgateway
    inputs:
      event: fileUploaded
      space: ${inputs.eventGatewaySpace}
      eventGatewayApiKey: ${inputs.eventGatewayApiKey}
      lambdaArn: ${downloaderLambda.arn}
