# TODO: Make this more reusable
type: s3-uploader
version: 0.0.1

inputTypes:
  name:
    type: string
    default: my-s3-uploader
  eventGatewaySpace:
    type: string
    required: true
  eventGatewayApiKey:
    type: string
    required: true

components:
  uploaderLambda:
    type: aws-lambda
    inputs:
      name: ${input.name}
      handler: uploader.handler
      env:
        EVENT_GATEWAY_APIKEY: ${inputs.eventGatewayApiKey}
        BUCKET: serverless-components-files
  uploaderSubscription:
    type: eventgateway
    inputs:
      event: http
      method: POST
      path: ${input.name}
      space: ${inputs.eventGatewaySpace}
      eventGatewayApiKey: ${inputs.eventGatewayApiKey}
      lambdaArn: ${uploaderLambda.arn}
