type: rest-api
version: 0.0.1

inputTypes:
  gateway:
    type: string
    required: true
  eventGatewayApiKey:
    type: string
    required: false
  space:
    type: string
    required: false
  name:
    type: string
    required: false
    default: api-${self.instanceId}
  routes:
    type: object
    required: true
