type: aws-cloudfront
version: 0.0.1

inputTypes:
  name:
    type: string
    required: false
    default: dist-${self.instanceId}
  defaultRootObject:
    type: string
    required: true
  originDomain:
    type: string
    required: true
  aliasDomain:
    type: string
  distributionEnabled:
    type: boolean
    default: true
  loggingEnabled:
    type: boolean
    default: false
  loggingBucket:
    type: string
    default: ''
  loggingIncludeCookies:
    type: boolean
    default: false
  loggingPrefix:
    type: string
    default: ''
  priceClass:
    type: string
